# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 16:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='artist_following',
            field=models.ManyToManyField(blank=True, null=True, related_name='artist_following', to='songs.Artist'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=user_profile.models.upload_to_profile),
        ),
    ]
