# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20161008_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='title_slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
