# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_album_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='name_slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='name_slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
