# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_auto_20161007_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
