# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_auto_20161008_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='album',
            name='name_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
